version: '2.2'

services:
  elasticsearch:
    # docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    #restart: always
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    volumes:
      - ./elasticsearch/custom_elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      #- ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    container_name: kibana
    environment:
      - "server.name=kibana"
      - "elasticsearch.hosts=http://elasticsearch:9200"
    ports:
      - 5601:5601
    networks:
      - elk
    links:
      - elasticsearch

  rest_malware:
    build:
      context: malware/
      dockerfile: Dockerfile
    container_name: rest_malware
    volumes:
      - ./malware/virustotal.db:/root/virustotal.db
    ports:
      - 8080:8080
    networks:
      - elk

  cowrie:
    # docker run -p 2222:2222 cowrie/cowrie
    image: procamora/cowrie:latest
    #build: '.'
    container_name: cowrie
    #restart: always
    volumes:
      - ./cowrie/etc/:/cowrie/cowrie-git/etc/
      - ./cowrie/log/:/cowrie/cowrie-git/var/log/cowrie/
    ports:
      - 2222:2222
    networks:
      - elk


networks:
  elk:
    driver: bridge
