#!/bin/env python3
# -*- coding: utf-8 -*-

import argparse  # https://docs.python.org/3/library/argparse.html
import configparser

from completeSessions import CompleteSession
from parser import Parser


def CreateArgParser():
    """
    Metodo para establecer los argumentos que necesita la clasek

    :return:
    """
    config = configparser.ConfigParser()
    config.sections()
    config.read('settings.conf')

    example = "\n\tExample of use to execute the Parser: python3 run.py -d /mnt/cowrie/ -o output/ -v" \
              "\n\tExample of use to execute CompleteSession: python3 run.py -o output/ -v"

    myParser = argparse.ArgumentParser(description='%(prog)s is a script to parse the log generated by the honeypot SSH\
 Cowrie and generate a JSON file with which to import the data into a BD NoSQL.', usage='{}'.format(example))

    myParser.add_argument('-d', '--dir', help='Directory where the files are located.')
    myParser.add_argument('-o', '--output', help='Directory where the generated files are stored.')
    myParser.add_argument('-db', '--mmdb', help='Path where the DB is in our SO.')
    myParser.add_argument('-v', '--verbose', action='store_true', help='Verbose flag (boolean).', default=False)

    # tambien lo puedo poner en la misma linea
    myParser.set_defaults(mmdb=config['DEFAULTS']['BD_GEOIP2'])
    myParser.set_defaults(output=config['DEFAULTS']['OUTPUT'])
    # myParser.print_help()
    return myParser.parse_args()


if __name__ == "__main__":
    arg = CreateArgParser()

    if arg.dir is not None:
        parser = Parser(arg.verbose, arg.output, arg.dir, 'DEFAULTS')
        parser.parse(arg.mmdb)
    else:
        c = CompleteSession(arg.verbose, arg.output, 'DEFAULTS')
        c.run()

