version: '2.2'

services:
  elasticsearch:
    # docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    restart: always
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    volumes:
      - ./elasticsearch/custom_elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      #- ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    container_name: kibana
    environment:
      - "server.name=kibana"
      - "elasticsearch.hosts=http://127.0.0.1:9200"
    ports:
      - 5601:5601
    networks:
      - elk
    links:
      - elasticsearch

networks:
  elk:
    driver: bridge
